import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);

// https://news-app-4d4c8-default-rtdb.europe-west1.firebasedatabase.app/

// {  "id": "a-162434770831",  "source": "Yahoo! News",  "publishDate": "2019-05-08T00:00:00Z",  "title": "Why Shares of MACOM Technology Jumped Today",  "body": "What happened\nShares of MACOM Technology Solutions Holdings (NASDAQ: MTSI) soared on Wednesday following a mixed fiscal second-quarter report. Revenue came in ahead of expectations, enough to overshadow an earnings miss. An analyst upgrade added fuel to the fire, propelling the stock up 30.6% by 11:50 a.m. EDT.\nSo what\nMACOM reported second-quarter adjusted revenue of $121.5 million, down 19.2% year over year but about $0.4 million above the average analyst estimate. The top line was hit hard by an inventory correction in the data center market, which was more disruptive than MACOM had initially expected.\nNon-GAAP (generally accepted accounting principles) earnings per share came in at a loss of $0.18, down from a profit of $0.13 in the prior-year period and $0.01 below analyst expectations. Adjusted earnings before interest, taxes, depreciation, and amortization was $3.4 million, down from $23.4 million one year ago.\nFor the third quarter, MACOM expects to produce revenue between $120 million and $124 million, along with a non-GAAP net loss per share between $0.04 and $0.08.\nNow what\nWhile the data center inventory correction is causing problems for MACOM, the company sees better days ahead. \"Some customers are indicating they will be exiting the quarter at more normalized inventory levels, which is a leading indicator of a recovery in the second half of the year,\" said MACOM president and CEO John Croteau.\nAnalysts from Craig-Hallum are on board with that story, upgrading the stock to \"buy\" on Wednesday and raising the price target from $17 to $25. Even after the post-earnings surge, shares of MACOM trade a bit below $17 per share.\nWhile MACOM's results were far from impressive, the promise of a second-half recovery and slightly higher-than-expected revenue was enough to push up the stock.\nMore From The Motley Fool\nTimothy Green has no position in any of the stocks mentioned. The Motley Fool has no position in any of the stocks mentioned. The Motley Fool has a disclosure policy."}
